"""
Test cases for the clformat.utils
"""
from .base import UTest, UTestSuite
from clformat.utils.radix import int_english


class UTCLUtils(UTest):
    def test_run(self):
        for value, result in self.cases:
            self.assertEqual(self.test_func(value), result)


class UTCLUtilsSpellInt(UTCLUtils):
    def test_func(self, *args, **kwargs):
        return int_english(*args)

    def set_cases(self):
        self.cases = [
            (123, 'one hundred and twenty-three'),
            (1234, 'one thousand, two hundred and thirty-four'),
            (255289518543814491432098796409352905856177383777363604004579629013,
             "two hundred and fifty-five vigintillion, two hundred and eighty-nine novemdecillion, five hundred and eighteen octodecillion, five hundred and forty-three septendecillion, eight hundred and fourteen sexdecillion, four hundred and ninety-one quindecillion, four hundred and thirty-two quattuordecillion, ninety-eight tredecillion, seven hundred and ninety-six duodecillion, four hundred and nine undecillion, three hundred and fifty-two decillion, nine hundred and five nonillion, eight hundred and fifty-six octillion, one hundred and seventy-seven septillion, three hundred and eighty-three sextillion, seven hundred and seventy-seven quintillion, three hundred and sixty-three quadrillion, six hundred and four trillion, four billion, five hundred and seventy-nine million, six hundred and twenty-nine thousand, thirteen"),
            (47138075959234993260830715993447643868277421019159922555962337881,
             "forty-seven vigintillion, one hundred and thirty-eight novemdecillion, seventy-five octodecillion, nine hundred and fifty-nine septendecillion, two hundred and thirty-four sexdecillion, nine hundred and ninety-three quindecillion, two hundred and sixty quattuordecillion, eight hundred and thirty tredecillion, seven hundred and fifteen duodecillion, nine hundred and ninety-three undecillion, four hundred and forty-seven decillion, six hundred and forty-three nonillion, eight hundred and sixty-eight octillion, two hundred and seventy-seven septillion, four hundred and twenty-one sextillion, nineteen quintillion, one hundred and fifty-nine quadrillion, nine hundred and twenty-two trillion, five hundred and fifty-five billion, nine hundred and sixty-two million, three hundred and thirty-seven thousand, eight hundred and eighty-one"),
            (344466606336927748761036638234469170631374694838799567179715192405,
             "three hundred and forty-four vigintillion, four hundred and sixty-six novemdecillion, six hundred and six octodecillion, three hundred and thirty-six septendecillion, nine hundred and twenty-seven sexdecillion, seven hundred and forty-eight quindecillion, seven hundred and sixty-one quattuordecillion, thirty-six tredecillion, six hundred and thirty-eight duodecillion, two hundred and thirty-four undecillion, four hundred and sixty-nine decillion, one hundred and seventy nonillion, six hundred and thirty-one octillion, three hundred and seventy-four septillion, six hundred and ninety-four sextillion, eight hundred and thirty-eight quintillion, seven hundred and ninety-nine quadrillion, five hundred and sixty-seven trillion, one hundred and seventy-nine billion, seven hundred and fifteen million, one hundred and ninety-two thousand, four hundred and five"),
            (912825648903203952259567811367177259165168485067340383186201412590,
             "nine hundred and twelve vigintillion, eight hundred and twenty-five novemdecillion, six hundred and forty-eight octodecillion, nine hundred and three septendecillion, two hundred and three sexdecillion, nine hundred and fifty-two quindecillion, two hundred and fifty-nine quattuordecillion, five hundred and sixty-seven tredecillion, eight hundred and eleven duodecillion, three hundred and sixty-seven undecillion, one hundred and seventy-seven decillion, two hundred and fifty-nine nonillion, one hundred and sixty-five octillion, one hundred and sixty-eight septillion, four hundred and eighty-five sextillion, sixty-seven quintillion, three hundred and forty quadrillion, three hundred and eighty-three trillion, one hundred and eighty-six billion, two hundred and one million, four hundred and twelve thousand, five hundred and ninety"),
            (144061934935887522920022170001572837365674530344651897206503090502,
             "one hundred and forty-four vigintillion, sixty-one novemdecillion, nine hundred and thirty-four octodecillion, nine hundred and thirty-five septendecillion, eight hundred and eighty-seven sexdecillion, five hundred and twenty-two quindecillion, nine hundred and twenty quattuordecillion, twenty-two tredecillion, one hundred and seventy duodecillion, one undecillion, five hundred and seventy-two decillion, eight hundred and thirty-seven nonillion, three hundred and sixty-five octillion, six hundred and seventy-four septillion, five hundred and thirty sextillion, three hundred and forty-four quintillion, six hundred and fifty-one quadrillion, eight hundred and ninety-seven trillion, two hundred and six billion, five hundred and three million, ninety thousand, five hundred and two"),
            (213237928859366463360504215556665026278769777174255212141589263865,
             "two hundred and thirteen vigintillion, two hundred and thirty-seven novemdecillion, nine hundred and twenty-eight octodecillion, eight hundred and fifty-nine septendecillion, three hundred and sixty-six sexdecillion, four hundred and sixty-three quindecillion, three hundred and sixty quattuordecillion, five hundred and four tredecillion, two hundred and fifteen duodecillion, five hundred and fifty-six undecillion, six hundred and sixty-five decillion, twenty-six nonillion, two hundred and seventy-eight octillion, seven hundred and sixty-nine septillion, seven hundred and seventy-seven sextillion, one hundred and seventy-four quintillion, two hundred and fifty-five quadrillion, two hundred and twelve trillion, one hundred and forty-one billion, five hundred and eighty-nine million, two hundred and sixty-three thousand, eight hundred and sixty-five"),
            (357959253193553126212237353216931965252155740645853316036816338591,
             "three hundred and fifty-seven vigintillion, nine hundred and fifty-nine novemdecillion, two hundred and fifty-three octodecillion, one hundred and ninety-three septendecillion, five hundred and fifty-three sexdecillion, one hundred and twenty-six quindecillion, two hundred and twelve quattuordecillion, two hundred and thirty-seven tredecillion, three hundred and fifty-three duodecillion, two hundred and sixteen undecillion, nine hundred and thirty-one decillion, nine hundred and sixty-five nonillion, two hundred and fifty-two octillion, one hundred and fifty-five septillion, seven hundred and forty sextillion, six hundred and forty-five quintillion, eight hundred and fifty-three quadrillion, three hundred and sixteen trillion, thirty-six billion, eight hundred and sixteen million, three hundred and thirty-eight thousand, five hundred and ninety-one"),
            (356235278871713896842050733755616961368742175704822883433396090959,
             "three hundred and fifty-six vigintillion, two hundred and thirty-five novemdecillion, two hundred and seventy-eight octodecillion, eight hundred and seventy-one septendecillion, seven hundred and thirteen sexdecillion, eight hundred and ninety-six quindecillion, eight hundred and forty-two quattuordecillion, fifty tredecillion, seven hundred and thirty-three duodecillion, seven hundred and fifty-five undecillion, six hundred and sixteen decillion, nine hundred and sixty-one nonillion, three hundred and sixty-eight octillion, seven hundred and forty-two septillion, one hundred and seventy-five sextillion, seven hundred and four quintillion, eight hundred and twenty-two quadrillion, eight hundred and eighty-three trillion, four hundred and thirty-three billion, three hundred and ninety-six million, ninety thousand, nine hundred and fifty-nine"),
            (840904866342449138059833500313710550723905493745709022176936236057,
             "eight hundred and forty vigintillion, nine hundred and four novemdecillion, eight hundred and sixty-six octodecillion, three hundred and forty-two septendecillion, four hundred and forty-nine sexdecillion, one hundred and thirty-eight quindecillion, fifty-nine quattuordecillion, eight hundred and thirty-three tredecillion, five hundred duodecillion, three hundred and thirteen undecillion, seven hundred and ten decillion, five hundred and fifty nonillion, seven hundred and twenty-three octillion, nine hundred and five septillion, four hundred and ninety-three sextillion, seven hundred and forty-five quintillion, seven hundred and nine quadrillion, twenty-two trillion, one hundred and seventy-six billion, nine hundred and thirty-six million, two hundred and thirty-six thousand, fifty-seven"),
            (395548363955893274399079710479504392275557564414756671303346195081,
             "three hundred and ninety-five vigintillion, five hundred and forty-eight novemdecillion, three hundred and sixty-three octodecillion, nine hundred and fifty-five septendecillion, eight hundred and ninety-three sexdecillion, two hundred and seventy-four quindecillion, three hundred and ninety-nine quattuordecillion, seventy-nine tredecillion, seven hundred and ten duodecillion, four hundred and seventy-nine undecillion, five hundred and four decillion, three hundred and ninety-two nonillion, two hundred and seventy-five octillion, five hundred and fifty-seven septillion, five hundred and sixty-four sextillion, four hundred and fourteen quintillion, seven hundred and fifty-six quadrillion, six hundred and seventy-one trillion, three hundred and three billion, three hundred and forty-six million, one hundred and ninety-five thousand, eighty-one"),
        ]


class UTCLUtilsSpellIntOrdinal(UTCLUtils):
    def test_func(self, *args, **kwargs):
        return int_english(*args, ordinal=True)

    def set_cases(self):
        self.cases = [
            (255289518543814491432098796409352905856177383777363604004579629013,
             "two hundred and fifty-five vigintillion, two hundred and eighty-nine novemdecillion, five hundred and eighteen octodecillion, five hundred and forty-three septendecillion, eight hundred and fourteen sexdecillion, four hundred and ninety-one quindecillion, four hundred and thirty-two quattuordecillion, ninety-eight tredecillion, seven hundred and ninety-six duodecillion, four hundred and nine undecillion, three hundred and fifty-two decillion, nine hundred and five nonillion, eight hundred and fifty-six octillion, one hundred and seventy-seven septillion, three hundred and eighty-three sextillion, seven hundred and seventy-seven quintillion, three hundred and sixty-three quadrillion, six hundred and four trillion, four billion, five hundred and seventy-nine million, six hundred and twenty-nine thousand thirteenth"),
            (47138075959234993260830715993447643868277421019159922555962337881,
             "forty-seven vigintillion, one hundred and thirty-eight novemdecillion, seventy-five octodecillion, nine hundred and fifty-nine septendecillion, two hundred and thirty-four sexdecillion, nine hundred and ninety-three quindecillion, two hundred and sixty quattuordecillion, eight hundred and thirty tredecillion, seven hundred and fifteen duodecillion, nine hundred and ninety-three undecillion, four hundred and forty-seven decillion, six hundred and forty-three nonillion, eight hundred and sixty-eight octillion, two hundred and seventy-seven septillion, four hundred and twenty-one sextillion, nineteen quintillion, one hundred and fifty-nine quadrillion, nine hundred and twenty-two trillion, five hundred and fifty-five billion, nine hundred and sixty-two million, three hundred and thirty-seven thousand, eight hundred eighty-first"),
            (344466606336927748761036638234469170631374694838799567179715192405,
             "three hundred and forty-four vigintillion, four hundred and sixty-six novemdecillion, six hundred and six octodecillion, three hundred and thirty-six septendecillion, nine hundred and twenty-seven sexdecillion, seven hundred and forty-eight quindecillion, seven hundred and sixty-one quattuordecillion, thirty-six tredecillion, six hundred and thirty-eight duodecillion, two hundred and thirty-four undecillion, four hundred and sixty-nine decillion, one hundred and seventy nonillion, six hundred and thirty-one octillion, three hundred and seventy-four septillion, six hundred and ninety-four sextillion, eight hundred and thirty-eight quintillion, seven hundred and ninety-nine quadrillion, five hundred and sixty-seven trillion, one hundred and seventy-nine billion, seven hundred and fifteen million, one hundred and ninety-two thousand, four hundred fifth"),
            (912825648903203952259567811367177259165168485067340383186201412590,
             "nine hundred and twelve vigintillion, eight hundred and twenty-five novemdecillion, six hundred and forty-eight octodecillion, nine hundred and three septendecillion, two hundred and three sexdecillion, nine hundred and fifty-two quindecillion, two hundred and fifty-nine quattuordecillion, five hundred and sixty-seven tredecillion, eight hundred and eleven duodecillion, three hundred and sixty-seven undecillion, one hundred and seventy-seven decillion, two hundred and fifty-nine nonillion, one hundred and sixty-five octillion, one hundred and sixty-eight septillion, four hundred and eighty-five sextillion, sixty-seven quintillion, three hundred and forty quadrillion, three hundred and eighty-three trillion, one hundred and eighty-six billion, two hundred and one million, four hundred and twelve thousand, five hundred ninetieth"),
            (144061934935887522920022170001572837365674530344651897206503090502,
             "one hundred and forty-four vigintillion, sixty-one novemdecillion, nine hundred and thirty-four octodecillion, nine hundred and thirty-five septendecillion, eight hundred and eighty-seven sexdecillion, five hundred and twenty-two quindecillion, nine hundred and twenty quattuordecillion, twenty-two tredecillion, one hundred and seventy duodecillion, one undecillion, five hundred and seventy-two decillion, eight hundred and thirty-seven nonillion, three hundred and sixty-five octillion, six hundred and seventy-four septillion, five hundred and thirty sextillion, three hundred and forty-four quintillion, six hundred and fifty-one quadrillion, eight hundred and ninety-seven trillion, two hundred and six billion, five hundred and three million, ninety thousand, five hundred second"),
            (213237928859366463360504215556665026278769777174255212141589263865,
             "two hundred and thirteen vigintillion, two hundred and thirty-seven novemdecillion, nine hundred and twenty-eight octodecillion, eight hundred and fifty-nine septendecillion, three hundred and sixty-six sexdecillion, four hundred and sixty-three quindecillion, three hundred and sixty quattuordecillion, five hundred and four tredecillion, two hundred and fifteen duodecillion, five hundred and fifty-six undecillion, six hundred and sixty-five decillion, twenty-six nonillion, two hundred and seventy-eight octillion, seven hundred and sixty-nine septillion, seven hundred and seventy-seven sextillion, one hundred and seventy-four quintillion, two hundred and fifty-five quadrillion, two hundred and twelve trillion, one hundred and forty-one billion, five hundred and eighty-nine million, two hundred and sixty-three thousand, eight hundred sixty-fifth"),
            (357959253193553126212237353216931965252155740645853316036816338591,
             "three hundred and fifty-seven vigintillion, nine hundred and fifty-nine novemdecillion, two hundred and fifty-three octodecillion, one hundred and ninety-three septendecillion, five hundred and fifty-three sexdecillion, one hundred and twenty-six quindecillion, two hundred and twelve quattuordecillion, two hundred and thirty-seven tredecillion, three hundred and fifty-three duodecillion, two hundred and sixteen undecillion, nine hundred and thirty-one decillion, nine hundred and sixty-five nonillion, two hundred and fifty-two octillion, one hundred and fifty-five septillion, seven hundred and forty sextillion, six hundred and forty-five quintillion, eight hundred and fifty-three quadrillion, three hundred and sixteen trillion, thirty-six billion, eight hundred and sixteen million, three hundred and thirty-eight thousand, five hundred ninety-first"),
            (356235278871713896842050733755616961368742175704822883433396090959,
             "three hundred and fifty-six vigintillion, two hundred and thirty-five novemdecillion, two hundred and seventy-eight octodecillion, eight hundred and seventy-one septendecillion, seven hundred and thirteen sexdecillion, eight hundred and ninety-six quindecillion, eight hundred and forty-two quattuordecillion, fifty tredecillion, seven hundred and thirty-three duodecillion, seven hundred and fifty-five undecillion, six hundred and sixteen decillion, nine hundred and sixty-one nonillion, three hundred and sixty-eight octillion, seven hundred and forty-two septillion, one hundred and seventy-five sextillion, seven hundred and four quintillion, eight hundred and twenty-two quadrillion, eight hundred and eighty-three trillion, four hundred and thirty-three billion, three hundred and ninety-six million, ninety thousand, nine hundred fifty-ninth"),
            (840904866342449138059833500313710550723905493745709022176936236057,
             "eight hundred and forty vigintillion, nine hundred and four novemdecillion, eight hundred and sixty-six octodecillion, three hundred and forty-two septendecillion, four hundred and forty-nine sexdecillion, one hundred and thirty-eight quindecillion, fifty-nine quattuordecillion, eight hundred and thirty-three tredecillion, five hundred duodecillion, three hundred and thirteen undecillion, seven hundred and ten decillion, five hundred and fifty nonillion, seven hundred and twenty-three octillion, nine hundred and five septillion, four hundred and ninety-three sextillion, seven hundred and forty-five quintillion, seven hundred and nine quadrillion, twenty-two trillion, one hundred and seventy-six billion, nine hundred and thirty-six million, two hundred and thirty-six thousand fifty-seventh"),
            (395548363955893274399079710479504392275557564414756671303346195081,
             "three hundred and ninety-five vigintillion, five hundred and forty-eight novemdecillion, three hundred and sixty-three octodecillion, nine hundred and fifty-five septendecillion, eight hundred and ninety-three sexdecillion, two hundred and seventy-four quindecillion, three hundred and ninety-nine quattuordecillion, seventy-nine tredecillion, seven hundred and ten duodecillion, four hundred and seventy-nine undecillion, five hundred and four decillion, three hundred and ninety-two nonillion, two hundred and seventy-five octillion, five hundred and fifty-seven septillion, five hundred and sixty-four sextillion, four hundred and fourteen quintillion, seven hundred and fifty-six quadrillion, six hundred and seventy-one trillion, three hundred and three billion, three hundred and forty-six million, one hundred and ninety-five thousand eighty-first"),
        ]


CASES = [UTCLUtilsSpellInt, UTCLUtilsSpellIntOrdinal]
